{{- if .Values.streaming.ingress.enabled -}}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- $fullName := include "mastodon.fullname" . -}}
{{- $svcPort := .Values.streaming.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-streaming
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  {{- with .Values.streaming.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.streaming.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.streaming.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{ if semverCompare ">=1.19-0" $gitVersion }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-streaming
                port:
                  number: {{ $svcPort }}
{{ else }}
          - path: /
            backend:
              serviceName: {{ $fullName }}-streaming
              servicePort: {{ $svcPort }}
{{- end }}
  {{- end }}
{{- end }}
